name: github-basic-actions
env:
  APPLICATION_NAME: "simple ci-cd test app"
  HASH_COMMIT: "${{ github.sha }}"

on:
  push:
    branches: 
      - main
      
jobs:

  testing_job:
    runs-on: ubuntu-22.04

    steps:
    
      - name: print hello message from testing_job
        run: echo "Hello World from testing_job"
        
      - name: print application name
        run: echo "this is app name => ${{ env.APPLICATION_NAME }}"

      - name: show directory info before cloning
        run: ls -l

      - name: cloning directory
        run: actions/checkout@v1

      - name: show directory info after cloning
        run: ls -l

  deploy_job:
    runs-on: ubuntu-22.04
    needs: testing_job

    steps:
    
      - name: print hello message from build_job
        run: echo "Hello world from build_job"

      - name: print commit hash
        run: echo "this is commit hash => ${{ env.HASH_COMMIT }}"
